Update .gitconfig
rzgry/dotfiles pull request #1
Opened 2019-11-11 14:39 UTC by jimmy1wu

2019-11-11 14:40 UTC, rzgry requested changes

2019-11-11 14:40 UTC, rzgry commented on .gitconfig
> +  name = Jimmy Wu
no

2019-11-11 21:14 UTC, kartikrajkanna commented
@jimmy1wu https://github.com/rzgry/dotfiles/pull/2
this is how u make PRs that get approved

2019-11-12 17:38 UTC, jimmy1wu commented on .gitconfig
> +  name = Jimmy Wu
understandable, have a nice day

2022-10-01 00:44 UTC, closed without merging